TravelTripProject/TravelTripProject/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProject.Models.Sınıflar;
namespace TravelTripProject.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Hakkimizdas.ToList();
            return View(degerler);
        }
    }
}

TravelTripProject/TravelTripProject/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProject.Models.Sınıflar;

namespace TravelTripProject.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        Context c = new Context();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }  
        
        [HttpPost]
        public ActionResult Index(Iletisim il)
        {
            c.Iletisims.Add(il);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        
       
    }
}

TravelTripProject/TravelTripProject/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>Admin | Uçan Bavul </title>
<link href="~/weblogin/images/admin.png" rel="icon" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="/Admin/Index/" class="w3-bar-item w3-button">Bloglar</a>
        <a href="/Admin/YorumListesi/" class="w3-bar-item w3-button">Yorumlar</a>
        <a href="/Admin/iletisimListesi/" class="w3-bar-item w3-button">İletişim</a>
      @*  <a href="/Admin/HakkimizdaListesi/" class="w3-bar-item w3-button">Hakkımızda</a>*@
        <a href="/Default/Index/" class="w3-bar-item w3-button">Siteye Git</a>
        <a href="/GirisYap/Logout/" class="w3-bar-item w3-button">Çıkış Yap</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h4>Admin Yönetim Paneli</h4>
        </div>

        <div class="w3-container">
          @RenderBody()
        </div>
    </div>
</body>
</html>

TravelTripProject/TravelTripProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Gezintiyi aç/kapat" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Giriş", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TravelTripProject/TravelTripProject/Views/Shared/_TestLayout.cshtml
@{
    Layout = null;
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web/images/svg.png" rel="icon" />
    <title>Gezi Günlüğüm | Uçan Bavul</title>
   
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="~/web/css/style.css" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/web/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web/js/jquery.min.js"></script>
    <script src="~/web/js/responsiveslides.min.js"></script>

    <script>
        // You can also use "$(window).load(function() {"
        $(function () {
            // Slideshow 1
            $("#slider1").responsiveSlides({
                auto: true,
                nav: true,
                speed: 500,
                namespace: "callbacks",
            });
        });
    </script>
</head>
<body>
    <div class="header">
        <div class="wrap">
            <div class="logo"><a href="index.html"><img src="~/web/images/Uçan Bavul (4).png" alt="" /></a></div>
            <div class="con-right">
                @*<div class="grid1-l-img">
                    <img src="~/web/images/contact.png" alt="">
                </div>
                <div class="grid1-l-desc">
                    <p>WhatsApp : +91 00000-55555</p>
                </div>*@
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="header-bottom">
        <div class="wrap">
            <ul id="nav">
                <li><a href="/Default/Index/">Ana Sayfa</a></li>
                <li><a class="hsubs" href="/About/Index/">Hakkımda</a></li>

                <li><a class="hsubs" href="/Blog/Index/">Blog</a></li>
                <li><a href="/Contact/Index/">İletişim</a></li>
                <li>
                    <a class="hsubs" href="/Admin/Index/">Kullanıcı Girişi</a>
                    @*<ul class="subs">
                <li><a href="#">Oteller</a></li>
                <li><a href="#">Restauranlar</a></li>
                <li><a href="#">Müzeler</a></li>
            </ul>*@
                </li>
            </ul>
        </div>
    </div>
    
    <div class"content">
        @RenderBody()
    </div>
    <div class="footer-bottom">
        <div class="wrap">
            <div class="copy">
                <p>&copy; 2023 Uçan Bavul. Tüm hakları saklıdır. | Design by <a href="http://w3layouts.com">W3Layouts</a></p>
            </div>
        </div>
    </div>
</body>
</html>